# potentially interesting additional data ----
#
# overview of land use, tenure and management: https://www150.statcan.gc.ca/n1/pub/95-634-x/2017001/article/54903-eng.htm
# land tenure: https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=3210023401
# greenhouse database: https://www.statcan.gc.ca/en/lode/databases/odg
# 2001 agricultural census at fine spatial level (but available only in html): https://www150.statcan.gc.ca/n1/pub/95f0301x/4151237-eng.htm

# extract files ----
#
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100002-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100018-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100019-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100029-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100042-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100116-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100120-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100129-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100130-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100154-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100155-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100159-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100160-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100212-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100353-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100416-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100417-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100418-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100419-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100420-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100263-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100421-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100424-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100425-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100426-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100427-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100428-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100452-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100432-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100360-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100365-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100356-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100358-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100359-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100361-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100364-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100370-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100371-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100372-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100373-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100374-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100378-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100249-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100406-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)
unzip(zipfile = paste0(census_dir, "adb_tables/stage1/statcan/32100456-eng.zip"),
      exdir = paste0(census_dir, "adb_tables/stage1/statcan"),
      overwrite = TRUE)

