
Hi Luise (cc Steffen),


Kurzer Nachtrag zu unserem Gespräch vorhin:


  ich bin gerade nochmal die Definitionen der PA categories durchgegangen. Tatsächlich ist Category V bzgl. Landnutzung weniger streng als Category VI:

  Category V: Protected Landscape/Seascape A protected area where the interaction of people and nature over time has produced an area of distinct character with significant ecological, biological, cultural and scenic value: and where safeguarding the integrity of this interaction is vital to protecting and sustaining the area and its associated nature conservation and other values.

Category VI: Protected areas that conserve ecosystems and habitats, together with associated cultural values and traditional natural resource management systems. They are generally large, with most of the area in a natural condition, where a proportion is under sustainable natural resource management and where low-level non-industrial use of natural resources compatible with nature conservation is seen as one of the main aims of the area.

Distinction Categories V & VI: Category VI emphasises the need to link nature conservation in natural areas whilst supporting sustainable livelihoods: conversely category V emphasises values from long-term interactions of people and nature in modified conditions. In category VI the emphasis is on sustainable use of environmental products and services (typically hunting, grazing, management of natural resources), whereas in category V the emphasis is on more intensive uses (typically agriculture, forestry, tourism). Category VI will usually be more “natural” than category V.


In puncto erlaubter Landnutzung (gar nicht vs. sustainable use manchmal erlaubt) unterscheiden sich Ia und Ib stärker als Ib und II, III, oder IV, da in allen letzteren mitunter sustainable use durch indigenous communities erlaubt ist, in 1a aber grundsätzlich gar keine Landnutzung. Für die Frage, welches die jeweils höchste Schutzstufe (I'm Sinne von "Landnutzung am striktesten verboten") pro Pixel ist, solltest du also Ib mit II, III, und IV, nicht mit Ia zusammenfassen, und außerdem VI zwischen IV und V platzieren. Die Unterschiede zwischen Ib, II, III und IV bzgl. erlaubter Landnutzung sind nicht so relevant, das die Unterschiede zwischen diesen Kategorien sich nur auf die Biodiversitäts- bzw. Naturschutzmanagementziele beziehen.

Indigenous Lands stehen bzgl. ihres "Naturschutzstatus" etwas parallel zu PAs. Bzgl. der indigenen Nutzungsrechte ist es aber in fast allen Ländern und für fast alle Unterkategorien von Indigenous so (und auch viele der Communal Areas, die sowieso meist nur sehr klein sind), dass gar keine kommerzielle Agrar- oder Forstnutzung betrieben werden darf, sondern nur subsistence use. Indigenous subsistence use kann aber wie gesagt von Categories Ib bis IV (und auch in V & VI) theoretisch überall erlaubt sein. Das heißt aber nicht I'm Umkehrschluss, dass alle Indigenous areas (die nicht auch glaichzeitig in WDPA als Kategorien Ib-IV gelisted werden) automatisch den gleich strengen Landnutzungsstatus wie IUCN Categorien Ib-IV haben, da bei den indigenous aeas die gleichzeitig PAs Categ. ib-IV sind, grundsätzlich Natur- bzw. Habitatschutz das Haupt-Managementziel ist, wohingegen bei "normalen" Indigenous aeas das primäre Management-Ziel lediglich der Erhalbt der traditionellen Lebensweise ist.


Insgesamt würde ich also folgende, etwas vereinfachte und gleichzeitig PAs und Indigenous-Areas zusammenfassende "Landnutzungs-Governance-Skala" anwenden (von strenge bis weniger strenge Reglementierung): "1 - no land use allowed" (nur PA-Categ. Ia), "2 - only very light and sustainable subsistence use may be allowed, but is not a primary management objective (but conservation)" (incl. PA-Categ. Ib, II, III, IV), "3 - Areas managed to maintain predominantly natural landscapes, with sustainable uses allowed (incl. subsistence, traditional, light commercial), but conservation being a primary management objective, alongside sustainable use" (nur PA-Categ. VI), "4 - Areas where only subsistence use is allowed, but conservation is not a primary management objective" (formell anerkannte Indigenous Areas), "5 - Areas managed to maintain predominantly culturally formed landscapes with conservation value, with sustainable uses (incl. more intensive use forms and also sustainable industrial uses), being the primary management objective" (nur PA-Categ. V), "6 - Areas that are de facto traditionally managed by indigenous peoples or other traditional communities, which follow traditional livestyles with mostly low-intensity subsistence uses, and which may actively work against uses by any outsiders, but without any formally recognized indigenous land rights and thus without any specific management plans that legally prohibit non-sustainable intensive and/or industrial land-uses" (alle nicht formell anerkannten Indigenous Areas).

Trotzdem würde ich, wie wie besprochen, die PA und Indigenous area-Datensätze erstmal getrennt vorbereiten. Durch die kohärente ordinale Skale kann man sie dann nach Belieben zusammenfassen oder getrennt betrachten (z.B. für Sensivitätsanalysen o.ä.).


Bei den Indigenous Areas wie besprochen nicht verschiedene Kategorien unterscheiden (da für unsere Fragestellung hier nicht von zentralem Interesse), sondern stattdessen einfach nur nach Status splitten in "4 - definitiv formell anerkannt" (z.B. "titled" o.ä.) und "6 - nicht definitiv formell anerkannt" (also entweder "in process", "unknown", etc). Hier würde ich auch wieder einfach die niedrigste Zahl pro Pixel und Jahr plotten, und bitte dran denken, dass Indigenous Lands in den Jahren bevor sie zu Status 4 wurden grundsätzlich bereits Status 6 hatten (denn die Indigenous peoples haben bereits dort gelebt und ihr Land de facto geclaimed und gemanaged, wenn auch nicht unbedingt offiziell anerkannt oder bekannterweise.


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 LG,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Carsten
